###
GET http://localhost:8000/products
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Mouse",
    "price": 200.00
}
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Notebook",
    "price": 2003.00
}